# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h2iToFlKBSrBK18RLrmtX3tkdBhamH_J
"""

#tuplas ejercicio N°7
#calcular el promedio de gastos por consulta
#mostrar el promedio en pantalla
#si el gasto promedio es mayor a 4500 mostrar un mensaje
Historial3=(9530,4120,4580,1500,890,7516,426)
suma = 0
p = len(Historial3)
for elemento in Historial3:
  suma += elemento 
promedio = suma//p
print("El gasto promedio de atencion es de: $",promedio)
if promedio>4500:  
  print("Se ha excedido del gasto promedio para su mascota")